### ISSUE TITLE
Selection options blocked by collapsed table columns

### ISSUE THREAD

**Issue by wnameless** [yidas/jquery-reflow-table#1]
As the title mentioned, if I put select tag inside a column, the selection options will be blocked by other collapsed table columns.

FYI, I am working with the bootstrap-select js library.

**Comment by yidas** [comment]
Hi @wnameless 

You can try [version 1.0.2](https://github.com/yidas/jquery-reflow-table/releases/tag/1.0.2) to check if this issue is resolved.

Thanks for your suggestion.

**Comment by wnameless** [comment]
Yes, the problem has been solved. BTW, I like this library very much. It integrates itself with jQuery DataTable gracefully. Nice work!

**Comment by yidas** [comment]
I'm so glad to hear that!

Cheers
